### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of null

### ISSUE THREAD

**Issue by ryanpcmcquen** [ryanpcmcquen/inkdrop_wiki_links#1]
This happens every time a link is clicked.

```
browser-main.js:1 Uncaught TypeError: Cannot read property 'match' of null
    at t.extractNoteIdFromURI (file:///C:/Users/rpcm/AppData/Local/inkdrop/app-5.2.0/resources/app.asar/browser-main.js:1:35003)
    at t.Z.openUri (file:///C:/Users/rpcm/AppData/Local/inkdrop/app-5.2.0/resources/app.asar/browser-main.js:1:46129)
    at e.exports.handleLinkClick (file:///C:/Users/rpcm/AppData/Local/inkdrop/app-5.2.0/resources/app.asar/browser-main.js:4:72521)
    at HTMLDocument.o (file:///C:/Users/rpcm/AppData/Local/inkdrop/app-5.2.0/resources/app.asar/browser-main.js:1:461603)
    at HTMLDocument.__trace__ (C:\Users\rpcm\AppData\Local\inkdrop\app-5.2.0\resources\app.asar\app\static\node_modules\@bugsnag\browser\dist\bugsnag.js:2231:34)
t.extractNoteIdFromURI @ browser-main.js:1
openUri @ browser-main.js:1
handleLinkClick @ browser-main.js:4
o @ browser-main.js:1
__trace__ @ <embedded>:50237
```

Maybe @craftzdog has some ideas?

**Comment by craftzdog** [comment]
What if returning `false` in `onClick` function?
I should check if the given URL is a string in the click handler btw.

**Comment by ryanpcmcquen** [comment]
I added that, but it didn't help unfortunately. @craftzdog
